### ISSUE TITLE
script to generate data missing

### ISSUE THREAD

**Issue by stineb** [computationales/sofunCalVal#4]
Subdirectory `./data/` contains the forcing and calibration target data for our standard benchmarking. The `README.md` states that:

_Contains data for benchmarking, as well as the script to generated said datasets._ 

However, the script is not part of the git repo. Missing?

@khufkens

**Comment by khufkens** [comment]
scripts are always in `analysis`

https://github.com/computationales/sofunCalVal/blob/main/analysis/00_prepare_fluxnet_driver_data.R

As per instructions at https://github.com/computationales/R_proj_template/blob/main/README.md#the-analysis-folder
